version: "2"
run:
  timeout: 10m
  modules-download-mode: readonly
  tests: true
linters:
  default: all
  disable:
    - asasalint
    - mnd
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gocognit
    - godox
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - importas
    - interfacebloat
    - intrange # todo: re-enable at some point and update to new style
    - ireturn
    - maintidx
    - makezero
    - modernize
    - musttag
    - nakedret
    - nestif
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    errcheck:
      check-blank: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
        - composites
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
          disabled: false
          arguments:
            - allowTypesBefore: "testing.TB,*testing.T,*testing.B,*testing.F"
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: var-declaration
        - name: var-naming
    lll:
      line-length: 150
  exclusions:
    generated: lax
    rules:
      - path: _test\.go$
        linters:
          - dupword
          - errcheck
          - exhaustive
          - goconst
          - gosec
      - path: /doc.go$
        linters:
          - lll
    warn-unused: true
