on:
    push:
      tags:
        - '*'
  
jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: viamrobotics/build-action@v1
        with:
          version: ${{ github.ref_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
          key-value: ${{ secrets.VIAM_DEV_API_KEY }}
          token: ${{ github.token }}
